<?php

define('IMAGE_CFG_MAX_ITEM_IMAGE_COUNT', 5);


define('IMAGE_CFG_HOME_DIR', DIRECTORY_SEPARATOR.'oop');
define('IMAGE_CFG_RESOURCES_PATH', 			BASE_PATH.DIRECTORY_SEPARATOR.'resources'.DIRECTORY_SEPARATOR);
define('IMAGE_CFG_ITEMPICS_PATH', 			BASE_PATH.DIRECTORY_SEPARATOR.'resources'.DIRECTORY_SEPARATOR.'itempics'.DIRECTORY_SEPARATOR);
define('IMAGE_CFG_USERPICS_PATH', 			BASE_PATH.DIRECTORY_SEPARATOR.'resources'.DIRECTORY_SEPARATOR.'userpics'.DIRECTORY_SEPARATOR);



