<?php
define('NEWS_TYPE_BASE', 1);

define('NEWS_TYPE_ITEM_MESSAGE', NEWS_TYPE_BASE + 0);
define('NEWS_TYPE_ITEM_LIKE',  NEWS_TYPE_BASE + 1);
define('NEWS_TYPE_ITEM_COMMENT',  NEWS_TYPE_BASE + 2);
//define('NEWS_TYPE_ITEM_MESSAGE',  NEWS_TYPE_BASE + 3);

define('NEWS_TYPE_ITEMOWNER_AGREED_ON_GIVE',  NEWS_TYPE_BASE + 4);

define('NEWS_TYPE_NEW_ITEM_BY_FRIEND',  NEWS_TYPE_BASE + 13);
define('NEWS_TYPE_USER_FOLLOWED',  NEWS_TYPE_BASE + 14);

define('NEWS_TYPE_ITEM_EXCHANGED_INFORM_ITEMOWNER',  NEWS_TYPE_BASE + 11);
define('NEWS_TYPE_ITEM_EXCHANGED_INFORM_DESIRER',  NEWS_TYPE_BASE + 12);

define('NEWS_TYPE_AGREEMENT_ACHIVED_FOR_SELL',  NEWS_TYPE_BASE + 5);
define('NEWS_TYPE_AGREEMENT_ACHIVED_FOR_BUY',  NEWS_TYPE_BASE + 6);

define('NEWS_TYPE_ITEMOWNER_CONFIRMED_WAITS_FOR_YOU',  NEWS_TYPE_BASE + 8);
define('NEWS_TYPE_DESIRER_CONFIRMED_WAITS_FOR_YOU',  NEWS_TYPE_BASE + 9);

define('NEWS_TYPE_ITEMOWNER_CONFIRMED_WAITS_FOR_DESIRER',  NEWS_TYPE_BASE + 7);
define('NEWS_TYPE_DESIRER_CONFIRMED_WAITS_FOR_ITEMOWNER',  NEWS_TYPE_BASE + 10);



/* PARAMETRE TIPLERI TANIMLAMALARI */
define('NEWS_PARAM_TYPE_USER', 1);
define('NEWS_PARAM_TYPE_ITEM', 2);
define('NEWS_PARAM_TYPE_TIME', 3);
define('NEWS_PARAM_TYPE_ITEMMESSAGE', 4);
define('NEWS_PARAM_TYPE_GROUP', 5);

/* ACTION TIPLERI TANIMLAMALARI */
define('NEWS_ACTION_TYPE_USER', 1);
define('NEWS_ACTION_TYPE_ITEM', 2);
define('NEWS_ACTION_TYPE_TIME', 3);
define('NEWS_ACTION_TYPE_ITEMMESSAGE', 4);
define('NEWS_ACTION_TYPE_GROUP', 5);